<?php 
 return array (
  'site_name' => 'Laravel_商城222',
  'site_keywords' => 'Laravel商城,ECshop,B2C',
  'site_description' => 'Laravel商城,一个专属于ECshop的网站',
  'close_site' => '否',
  'logo' => '2018-10-22/e1e3fd94df9718ab39ed018c0ac9fd2c.jpg',
  'reg' => '开启',
  'ewm' => '2018-10-08/b37e713d42b2c908033486644e0f25cc.jpg',
  'search_keywords' => '周大福,内衣,Five,Plus,手机',
  'search_value' => 'mackpro',
  'cache' => '是',
  'cache_time' => '20',
  'Is_it_open_auth' => '否',
  'auth_hide_left' => '否',
  'list_page' => '5',
  'error_template' => 'think',
  'layer_style' => '1',
  'list_order' => 'asc',
  'cate_char' => '--',
  'cate_char_count' => '10',
  'is_check_code' => '是',
  'is_open_rbac' => '是',
);